# If the user arrives at root with their accept-language set, 
#  redirect to a localized version of the site
#
# otherwise serve site of root url.

[[redirects]]
  from = "/"
  to = "/es/"
  status = 301
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/"
  to = "/zh/"
  status = 301
  conditions = {Language = ["zh"]}

[[redirects]]
  from = "/"
  to = "/fr/"
  status = 301
  conditions = {Language = ["fr"]}

[[redirects]]
  from = "/"
  to = "/de/"
  status = 301
  conditions = {Language = ["de"]}

[[redirects]]
  from = "/"
  to = "/it/"
  status = 301
  conditions = {Language = ["it"]}

[[redirects]]
  from = "/"
  to = "/jp/"
  status = 301
  conditions = {Language = ["jp"]}

[[redirects]]
  from = "/"
  to = "/pt/"
  status = 301
  conditions = {Language = ["pt"]}

[[redirects]]
  from = "/"
  to = "/th/"
  status = 301
  conditions = {Language = ["th"]}

[[redirects]]
  from = "/"
  to = "/pl/"
  status = 301
  conditions = {Language = ["pl"]}

[[redirects]]
  from = "/"
  to = "/en/"
  status = 301
  conditions = {Language = ["en"]}
